name: CI Checks

on: [pull_request]

jobs:
  rust:
    name: Rust Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Cargo Check
        run: cargo check --all-targets --all-features
      - name: Rustfmt Check
        run: cargo fmt --all -- --check
      - name: Clippy Lint
        run: cargo clippy --all --all-features -- -D warnings

  elixir:
    name: Elixir Quality Checks
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      PACT_VERIFIER_EX_FORCE_BUILD: true
    steps:
      - uses: actions/checkout@v6
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.16
          otp-version: 25
      - name: Install pact-plugin-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-plugins/main/scripts/install-plugin-cli.sh | bash
          echo "$HOME/.pact/bin" >> $GITHUB_PATH
      - name: Install Pact CSV plugin
        run: |
          pact-plugin-cli install csv
      - name: Install dependencies
        run: mix deps.get
      - name: Format Check
        run: mix format --check-formatted
      - name: Credo Lint
        run: mix credo --strict
      - name: Dialyzer Analysis
        run: mix dialyzer
      - name: Test
        run: mix test

